#!/bin/sh

branchname="$(git rev-parse --abbrev-ref HEAD)"
validbranchregex="(hotfix|feature|release|bugfix)\/([A-Z]+\-[0-9]+).*"
[[ $branchname =~ $validbranchregex ]]
taskname=${BASH_REMATCH[2]}

commitedtaskname="$(grep '(^[A-Z]+\-[\d]+)' $1)"

if [[ ! $taskname =~ $commitedtaskname ]]
then
	echo "Task $commitedtaskname does not match branch $taskname. This is case sensitive"
	exit 2
fi
