#!/bin/sh

# Redirect output to stderr.
exec 1>&2

branchname="$(git rev-parse --abbrev-ref HEAD)"
validbranchname="(hotfix|feature|release|bugfix)\/([A-Z]+\-[\d]+)"

echo $branchname

if [[ ! $branchname =~ $valid_branch_regex ]]
then
    echo >&2 "There is something wrong with your branch name. Branch names in this project must adhere to this contract: $validbranchname. Your commit will be rejected."
    exit 1
fi

commitedtaskname="$(grep '([A-Z]+\-[\d]+)', "$1")"
taskname=${BASH_REMATCH[2]}

echo $taskname

if [[ ! $taskname == $commitedtaskname ]]
then
	echo >&2 "Task $commitedtaskname does not match branch $taskname. This is case sensitive"
	exit 2
fi