#!/bin/bash

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# Regex explanation:
# First group matches the branch type
# then we match a slash (/).
# After this we match one out of two things:
# The ticket number, not case sensitive, OR
# the number. This is to support release branches.
valid_branch_regex="^(hotfix|feature|release|bugfix)\/([a-zA-Z]+\-[0-9]+|[0-9]\..*).*"
branch_name="$(git rev-parse --abbrev-ref HEAD)"

if [[ ! $branch_name =~ $valid_branch_regex ]]
then
    echo "Commit error!"
    echo "The branch '$branch_name' is not named according to our standards."
    echo ""
    echo "Expected format:"
    echo "  $valid_branch_regex"
    echo ""
    echo "Examples:"
    echo "  feature/dx-839_some_great_description"
    echo "  release/1.8.1"
    echo "  hotfix/dx-123_very_hot_fix"
    exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
