#!/bin/bash

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# Regex explanation:
# First group matches the branch type
# then we match a slash (/).
# After this we match one out of two things:
# The ticket number, not case sensitive, OR
# the number. This is to support release branches.
valid_branch_regex="^(hotfix|feature|release|bugfix)\/([a-zA-Z]+\-[0-9]+|[0-9]\..*).*"
branch_name="$(git rev-parse --abbrev-ref HEAD)"

if [[ ! $branch_name =~ $valid_branch_regex ]]
then
    echo "Commit error!"
    echo "The branch '$branch_name' is not named according to our standards."
    echo ""
    echo "Expected format:"
    echo "  $valid_branch_regex"
    echo ""
    echo "Examples:"
    echo "  feature/dx-839_some_great_description"
    echo "  release/1.8.1"
    echo "  hotfix/dx-123_very_hot_fix"
    exit 1
fi

task_id=${BASH_REMATCH[2]}

echo "$task_id"' '$(cat "$COMMIT_MSG_FILE") > "$COMMIT_MSG_FILE"
