pull_request_rules:
  - name: Automatic approve on dependabot PR
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      review:
        type: APPROVE

  - name: Automatic merge on approval
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - '#commits-behind=0' # Only merge up to date pull requests
      - check-success=license/cla
      - check-success=shellcheck
      - check-success=variables
      - check-success=build
      - check-success=spec
      - "-body~=swedbank-pay-design-guide-jekyll-theme" # Don't merge if the PR contains the string "swedbank-pay-design-guide-jekyll-theme"
    actions:
      merge:

  - name: Thank contributor
    conditions:
      - merged
      - -author~=^.*\[bot\]$
    actions:
      comment:
        message: "Thank you @{{author}} for your contribution!"
