allow:
  - american
  - attacks
  - basically
  - black
  - blacklist
  - buried
  - clearly
  - color
  - colors
  - deposit
  - desire
  - dirty
  - easy
  - execute
  - executed
  - executes
  - execution
  - European
  - failed
  - failure
  - failures
  - funeral
  - german
  - harder
  - hook
  - hooks
  - host-hostess
  - hostesses-hosts
  - invalid
  - just
  - liberal
  - lies
  - master
  - obvious
  - of-course
  - period
  - POP
  - postman-postwoman
  - prince-princess
  - pros
  - reject
  - remain
  - remains
  - savage
  - simple
  - special
  - white
  - whitelist
  - whitelisting
  - whitespace
  - straightforward
  - bigger
