allow:
  - american
  - basically
  - buried
  - clearly
  - deposit
  - desire
  - dirty
  - easy
  - execute
  - executed
  - executes
  - failed
  - failure
  - failures
  - funeral
  - german
  - harder
  - hook
  - hooks
  - host-hostess
  - hostesses-hosts
  - invalid
  - just
  - liberal
  - master
  - obvious
  - of-course
  - period
  - postman-postwoman
  - prince-princess
  - pros
  - reject
  - remain
  - savage
  - simple
  - special
  - whitespace
  - straightforward
  - bigger
