name: Deploy to Azure Production CommonSvc
on:
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: |
          docker compose run \
            -e GITHUB_BRANCH=develop \
            -e GITHUB_REPOSITORY_URL=https://github.com/SwedbankPay/developer.swedbankpay.com \
            portal build \
            --env=production \
            --site-url=https://developer.swedbankpay.com

      - name: login
        uses: azure/login@v1.5.1
        with:
          creds: '{"clientId":"${{ secrets.SUBSCRIPTION_CLIENT_ID_PROD }}","clientSecret":"${{ secrets.SUBSCRIPTION_CLIENT_SECRET_PROD }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID_PROD }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      - name: deploy
        uses: azure/CLI@v1.0.9
        with:
          inlineScript: az storage blob upload-batch -s _site -d "\$web" --account-name proddevelopersa1 --overwrite
