name: Jekyll Build and Elasticsearch Indexing

on:
  push:
    branches: ['index-to-elasticsearch']

jobs:
  build-and-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Build Jekyll site
      run: |
        bundle install
        bundle exec jekyll build

    # New step: Install wkhtmltopdf
    - name: Install wkhtmltopdf
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf

    # New step: Generate PDF
    - name: Generate PDF
      working-directory: ./_site
      run: |
        wkhtmltopdf --enable-local-file-access all_content.html full_site.pdf

    # New step: Upload PDF to Azure Storage
    - name: Upload PDF to Azure Storage
      run: |
        az storage blob upload \
          --container-name pdf \
          --file "_site/full_site.pdf" \
          --name "full_site.pdf" \
          --account-name stagedeveloperecomsa2 \
          --overwrite