name: Jekyll Build and Elasticsearch Indexing

on:
  push:
    branches: ['index-to-elasticsearch']
jobs:
  build-and-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Configure Elasticsearch for Jekyll
      run: |
        echo "elasticsearch:" >> _config.yml
        echo "  url: ${{ secrets.ELASTICSEARCH_HOST }}" >> _config.yml
        echo "  api_key: ${{ secrets.ELASTICSEARCH_CLOUD_API_KEY_DEV }}" >> _config.yml
        echo "  number_of_shards: 1" >> _config.yml
        echo "  number_of_replicas: 1" >> _config.yml
        echo "  index_name: 'data-ecom.developer-1'" >> _config.yml
        echo "  default_type: 'post'" >> _config.yml

    - name: Install searchyll and Build Jekyll Site
      run: |
        echo "group :jekyll_plugins do" >> Gemfile
        echo "  gem 'searchyll'" >> Gemfile
        echo "end" >> Gemfile
        bundle install
        bundle exec jekyll build
      env:
        ELASTICSEARCH_URL: ${{ secrets.ELASTICSEARCH_HOST }}
        # Add other environment variables if required by your Elasticsearch setup

