name: Deploy to documents to Elasticsearch

on:
  push:
    branches: ['index-to-elasticsearch']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: jekyll build
        run: |
          docker compose run \
            -e GITHUB_BRANCH=develop \
            -e GITHUB_REPOSITORY_URL=https://github.com/SwedbankPay/developer.swedbankpay.com \
            portal build \
            --env=production \
            --site-url=https://developer.stage.swedbankpay.com
          
      - name: Install Nokogiri gem
        run: |
          gem install nokogiri --user-install
          echo "PATH=$PATH:$(ruby -e 'puts Gem.user_dir')/bin" >> $GITHUB_ENV
          

      - name: Index Processed HTML files to Elasticsearch
        run: |
          echo "Environment prefix is dev"
          echo "Version is 1"
          for html_file in $(find ./_site -name "*.html")
          do
            JSON_PAYLOAD=$(ruby .github/scripts/parse_html.rb $html_file)
            
            # Define the Elasticsearch URL
            URL="https://${{ secrets.ELASTICSEARCH_HOST }}/data-ecom-developer-1/_doc"
            
            echo "Indexing $html_file to $URL"
            curl --fail-with-body -X POST "$URL" \
            -H 'Content-Type: application/json' \
            -H 'Authorization: ApiKey ${{ secrets.ELASTICSEARCH_CLOUD_API_KEY_DEV }}' \
            -d "$JSON_PAYLOAD" || exit $?
          done
