name: Jekyll Build and Elasticsearch Indexing

on:
  push:
    branches: ['index-to-elasticsearch']

jobs:
  build-and-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install required gems
      run: |
        gem install nokogiri elasticsearch

    - name: Build Jekyll site
      run: |
        bundle install
        bundle exec jekyll build

    - name: Index Processed HTML files to Elasticsearch
      run: ruby .github/scripts/index_to_es.rb
      env:
        ELASTICSEARCH_URL: ${{ secrets.ELASTICSEARCH_HOST }}
        ELASTICSEARCH_API_KEY: ${{ secrets.ELASTICSEARCH_CLOUD_API_KEY_DEV }}
