name: Deploy to Azure Stage

on:
  push:
    branches: ['index-to-elasticsearch']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: jekyll build
        run: |
          docker compose run \
            -e GITHUB_BRANCH=develop \
            -e GITHUB_REPOSITORY_URL=https://github.com/SwedbankPay/developer.swedbankpay.com \
            portal build \
            --env=production \
            --site-url=https://developer.stage.swedbankpay.com
          
      - name: Index Processed HTML files to Elasticsearch
        run: |
          echo "Environment prefix is dev"
          echo "Version is 1"
          for html_file in $(find ./_site -name "*.html")
          do
            # Extract content and metadata from the processed HTML files
            # You may need to adjust the selectors based on your HTML structure
            TITLE=$(pup 'title text{}' < $html_file)
            CONTENT=$(pup 'body text{}' < $html_file)
            # Add extraction for other fields as necessary
            
            # Construct the URL
            URL_PATH="${html_file#./_site}"  # Strips the ./_site prefix
            
            # Create a JSON payload
            JSON_PAYLOAD=$(jq -n \
                              --arg id "$html_file" \
                              --arg url "$URL_PATH" \
                              --arg text "$CONTENT" \
                              --arg title "$TITLE" \
                              '{id: $id, url: $url, text: $text, title: $title}')
            
            # Define the Elasticsearch URL
            URL="https://${{ secrets.ELASTICSEARCH_HOST }}/dev-developer-1/_doc"
            
            echo "Indexing $html_file to $URL"
            curl --fail-with-body -X POST "$URL" \
            -H 'Content-Type: application/json' \
            -H 'Authorization: ApiKey ${{ secrets.ELASTICSEARCH_API_KEY }}' \
            -d "$JSON_PAYLOAD" || exit $?
          done
        env:
          PUP_PATH: "/path/to/pup"  # Set this to the path of the pup binary if it's not in the PATH by default
          
