name: Jekyll Build and Elasticsearch Indexing

on:
  push:
    branches: ['index-to-elasticsearch']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Jekyll Build
        run: |
          docker compose run \
            -e GITHUB_BRANCH=index-to-elasticsearch \
            -e GITHUB_REPOSITORY_URL=https://github.com/SwedbankPay/developer.swedbankpay.com \
            portal build \
            --env=production \
            --site-url=https://developer-ecom.stage.swedbankpay.com


      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Generate PDF
        working-directory: ./_site
        run: |
          wkhtmltopdf --enable-local-file-access "file://$(pwd)/all_content.html" full_site.pdf

      - name: azure login
        uses: azure/login@v2.2.0
        with:
          creds: '{"clientId":"${{ secrets.SUBSCRIPTION_CLIENT_ID_STAGE }}","clientSecret":"${{ secrets.SUBSCRIPTION_CLIENT_SECRET_STAGE }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID_STAGE }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      - name: Upload PDF to Azure Storage
        run: |
          az storage blob upload \
            --container-name pdf \
            --file "_site/full_site.pdf" \
            --name "full_site.pdf" \
            --account-name stagedeveloperecomsa2 \
            --overwrite
