name: Build Search Index

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: payex-dev
          GITHUB_ACTOR_EMAIL: dev@payex.com
          GITHUB_REPO: ${{ github.repository }}
        run: |
          docker compose run \
            -e GITHUB_BRANCH=develop \
            -e GITHUB_REPOSITORY_URL=https://github.com/SwedbankPay/developer.swedbankpay.com \
            -e ELASTICSEARCH_API_KEY=${{ secrets.ELASTICSEARCH_API_KEY_STAGE}} \
            -e ELASTICSEARCH_URL=${{ secrets.ELASTICSEARCH_API_URL_STAGE}} \
            portal build \
            --env=production \
            --site-url=https://developer.stage.swedbankpay.com
