name: Githooks

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Shellcheck
      uses: bewuethr/shellcheck-action@80bac2daa9fcf95d648200a793d00060857e6dc4 # v2.3.0

  commit-msg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Valid commit messages
      shell: bash
      run: bash ./.github/scripts/commit-msg-test.sh

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Valid branch names
      shell: bash
      run: |
        git checkout -b feature/dx-123_hello
        bash ./.githooks/pre-commit

    - name: Invalid branch names
      shell: bash
      run: |
        git checkout -b feature/hello
        bash ./.githooks/pre-commit
